### ISSUE TITLE
Configurar ambiente

### ISSUE THREAD

**Issue by marrcelo** [MDS-Mandacaru/TBL#2]
* Sistema operacional https://victorarnaud.github.io/TBL/contribuicao/install/
* ZenHub https://www.zenhub.com/

  **Tarefas:**  

    * [ ] Cada integrante deve comentar na Issue um checklist sobre o andamento da configuração do ambiente.

**Comment by marrcelo** [comment]
Ambiente configurado.

**Comment by williamelias** [comment]
Ambiente configurado

**Comment by aline-lv** [comment]
Ambiente configurado.

**Comment by miltonjuliano** [comment]
Ambiente configurado.

**Comment by LuisCL94** [comment]
Ambiente Configurado
